docs: new install instructions
ibm-telemetry/telemetry-js pull request #161
Opened 2023-12-26 21:53 UTC by francinelucca

Add new install instructions to readme file, no longer use npx for postinstall script

#### Changelog

**Changed**

- Modify onboarding instructions to install @ibm/telemetry-js directly onto instrumented project and call local copy on postinstall script

#### Testing / reviewing

N/A

2023-12-27 14:27 UTC, mattrosno requested changes

2023-12-27 14:27 UTC, mattrosno commented on README.md
> +#### 6. Publish a new version of your package.
```suggestion
### 6. Publish a new version of your package.
```

This was originally the wrong heading.

2023-12-27 14:27 UTC, mattrosno commented on README.md
> +#### 7. Done!
```suggestion
### 7. Done!
```

This was originally the wrong heading.

2023-12-27 14:27 UTC, mattrosno commented on README.md
> +### 3. Install `@ibm/telemetry-js` dependency
```suggestion
### 3. Install `@ibm/telemetry-js` dependency.
```

Other steps end periods.

2024-01-04 21:13 UTC, jdharvey-ibm approved these changes

2024-01-04 21:21 UTC, mattrosno approved these changes

2024-01-04 21:27 UTC, merged